const TIMEZONE_COUNTRIES: Record<string, string> = {
  "Europe/Moscow": "Russia",
  "Europe/London": "United Kingdom",
  "Europe/Paris": "France",
  "Europe/Berlin": "Germany",
  "Europe/Madrid": "Spain",
  "Europe/Rome": "Italy",
  "Europe/Oslo": "Norway",
  "Europe/Stockholm": "Sweden",
  "Europe/Copenhagen": "Denmark",
  "Europe/Amsterdam": "Netherlands",
  "Europe/Brussels": "Belgium",
  "Europe/Lisbon": "Portugal",
  "Europe/Athens": "Greece",
  "Europe/Istanbul": "Turkey",
  "Europe/Warsaw": "Poland",
  "Europe/Helsinki": "Finland",
  "Europe/Tallinn": "Estonia",
  "Europe/Riga": "Latvia",
  "Europe/Vilnius": "Lithuania",
  "Europe/Bucharest": "Romania",
  "Europe/Prague": "Czech Republic",
  "Europe/Budapest": "Hungary",
  "Europe/Vienna": "Austria",
  "Europe/Zurich": "Switzerland",
  "Europe/Dublin": "Ireland",
  "Europe/Belgrade": "Serbia",
  "Europe/Sofia": "Bulgaria",
  "Europe/Zagreb": "Croatia",
  "Europe/Kiev": "Ukraine",
  "Europe/Minsk": "Belarus",
  "Asia/Tokyo": "Japan",
  "Asia/Shanghai": "China",
  "Asia/Seoul": "South Korea",
  "Asia/Bangkok": "Thailand",
  "Asia/Ho_Chi_Minh": "Vietnam",
  "Asia/Jakarta": "Indonesia",
  "Asia/Kolkata": "India",
  "Asia/Dubai": "UAE",
  "Asia/Singapore": "Singapore",
  "Asia/Hong_Kong": "Hong Kong",
  "Asia/Taipei": "Taiwan",
  "Asia/Manila": "Philippines",
  "Asia/Vladivostok": "Russia",
  "Asia/Yekaterinburg": "Russia",
  "Asia/Novosibirsk": "Russia",
  "America/New_York": "United States",
  "America/Chicago": "United States",
  "America/Denver": "United States",
  "America/Los_Angeles": "United States",
  "America/Toronto": "Canada",
  "America/Vancouver": "Canada",
  "America/Sao_Paulo": "Brazil",
  "America/Argentina/Buenos_Aires": "Argentina",
  "America/Santiago": "Chile",
  "America/Lima": "Peru",
  "America/Mexico_City": "Mexico",
  "America/Bogota": "Colombia",
  "Pacific/Auckland": "New Zealand",
  "Australia/Sydney": "Australia",
  "Australia/Melbourne": "Australia",
  "Africa/Lagos": "Nigeria",
  "Africa/Johannesburg": "South Africa",
  "Africa/Nairobi": "Kenya",
  "Africa/Casablanca": "Morocco",
  "Atlantic/Reykjavik": "Iceland",
};

export function detectCountry(): string {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    return TIMEZONE_COUNTRIES[tz] || "";
  } catch {
    return "";
  }
}

export const SEAFOOD_COUNTRIES = [
  "Argentina", "Australia", "Belgium", "Brazil", "Canada", "Chile", "China",
  "Colombia", "Croatia", "Czech Republic", "Denmark", "Ecuador", "Estonia",
  "Finland", "France", "Germany", "Greece", "Hong Kong", "Hungary",
  "Iceland", "India", "Indonesia", "Ireland", "Italy", "Japan", "Kenya",
  "Latvia", "Lithuania", "Mexico", "Morocco", "Netherlands", "New Zealand",
  "Nigeria", "Norway", "Peru", "Philippines", "Poland", "Portugal",
  "Romania", "Russia", "Serbia", "Singapore", "South Africa", "South Korea",
  "Spain", "Sweden", "Switzerland", "Taiwan", "Thailand", "Turkey", "UAE",
  "Ukraine", "United Kingdom", "United States", "Vietnam",
];
